[package]
name = "psrec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = { version = "3.2.2", default-features = false, features = ["cpu", "process"] }
ctrlc = "3.2.3"
argh = "0.1.8"
